# Generated by Django 2.2.5 on 2019-09-21 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Registered')),
                ('contact_no', models.BigIntegerField(default=91, verbose_name='Contact Number')),
                ('blood_type', models.CharField(max_length=3, verbose_name='Blood Type')),
                ('aadhar', models.CharField(max_length=12, verbose_name='Aadhar Number')),
                ('status', models.CharField(default='Active', max_length=12, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Registered')),
                ('contact_no', models.BigIntegerField(default=91, verbose_name='Contact Number')),
                ('verify_status', models.CharField(default='Pending', max_length=12, verbose_name='Status')),
                ('MICID', models.CharField(max_length=50, verbose_name='MICID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoantionLogDetails',
            fields=[
                ('unit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unit ID')),
                ('donation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Donation ID')),
                ('blood_type', models.CharField(max_length=3, verbose_name='Blood Type')),
                ('amount', models.IntegerField(verbose_name='Amount in ml')),
                ('donated_from', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rel_donated_from', to=settings.AUTH_USER_MODEL)),
                ('donated_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rel_donated_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Registered')),
                ('contact_no', models.BigIntegerField(default=91, verbose_name='Contact Number')),
                ('a_positive', models.IntegerField(default=0, verbose_name='A+')),
                ('a_negative', models.IntegerField(default=0, verbose_name='A-')),
                ('b_positive', models.IntegerField(default=0, verbose_name='B+')),
                ('b_negative', models.IntegerField(default=0, verbose_name='B-')),
                ('o_positive', models.IntegerField(default=0, verbose_name='O+')),
                ('o_negative', models.IntegerField(default=0, verbose_name='O-')),
                ('ab_positive', models.IntegerField(default=0, verbose_name='AB+')),
                ('ab_negative', models.IntegerField(default=0, verbose_name='AB-')),
                ('MICID', models.CharField(max_length=50, verbose_name='MICID')),
                ('verify_status', models.CharField(default='Pending', max_length=12, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=60, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('zipcode', models.CharField(max_length=6, verbose_name='Zipcode')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
