# Generated by Django 2.2.5 on 2019-09-21 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doantionlogdetails',
            name='donated_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='rel_donated_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doantionlogdetails',
            name='donated_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='rel_donated_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
