# Generated by Django 2.2.5 on 2019-09-21 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcare', '0003_auto_20190921_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doantionlogdetails',
            name='donation_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Donation ID'),
        ),
        migrations.AlterField(
            model_name='doantionlogdetails',
            name='unit_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Unit ID'),
        ),
    ]
