# Generated by Django 2.2.7 on 2019-11-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcare', '0004_auto_20190921_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
